package io.persephone.dsl.element

import io.persephone.dsl.Tag
import io.persephone.dsl.element.*

// generated by HtmlDslGenerator.kt
class BASE(
	href: String? = null,
	target: String? = null
) : Tag(tagName = "base", selfClosing = true) {

	var href: String?
		get() = attributes.get("href")
		set(value) {
			value?.let {
				attributes["href"] = it
			}
		}

	var target: String?
		get() = attributes.get("target")
		set(value) {
			value?.let {
				attributes["target"] = it
			}
		}

	init {
		this.href = href
		this.target = target
	}
}
