package io.persephone.dsl.element

import io.persephone.dsl.HeadTag

// generated by Generator.kt [generateChildElements]
class BASE : HeadTag("base") {

	var href: String?
		get() = attributes.getOrDefault("href", "")
		set(value) {
			value?.let {
				attributes["href"] = it
			}
		}

	var target: String?
		get() = attributes.getOrDefault("target", "")
		set(value) {
			value?.let {
				attributes["target"] = it
			}
		}

}

