package io.persephone.dsl.element

import io.persephone.dsl.*

// generated by Generator.kt [process]
class BASE : EmptyTag("base") {

	var classes: String?
		get() = attributes.getOrDefault("classes", "")
		set(value) {
			value?.let {
				attributes["classes"] = it
			}
		}

	var href: String?
		get() = attributes.getOrDefault("href", "")
		set(value) {
			value?.let {
				attributes["href"] = it
			}
		}

	var styles: String?
		get() = attributes.getOrDefault("styles", "")
		set(value) {
			value?.let {
				attributes["styles"] = it
			}
		}

	var target: String?
		get() = attributes.getOrDefault("target", "")
		set(value) {
			value?.let {
				attributes["target"] = it
			}
		}

}

