package io.persephone.dsl.element

import io.persephone.dsl.*

// generated by Generator.kt [process]
class BUTTON : BodyTag("button") {

	var autocomplete: String?
		get() = attributes.getOrDefault("autocomplete", "")
		set(value) {
			value?.let {
				attributes["autocomplete"] = it
			}
		}

	var autofocus: String?
		get() = attributes.getOrDefault("autofocus", "")
		set(value) {
			value?.let {
				attributes["autofocus"] = it
			}
		}

	var classes: String?
		get() = attributes.getOrDefault("classes", "")
		set(value) {
			value?.let {
				attributes["classes"] = it
			}
		}

	var disabled: String?
		get() = attributes.getOrDefault("disabled", "")
		set(value) {
			value?.let {
				attributes["disabled"] = it
			}
		}

	var form: String?
		get() = attributes.getOrDefault("form", "")
		set(value) {
			value?.let {
				attributes["form"] = it
			}
		}

	var formaction: String?
		get() = attributes.getOrDefault("formaction", "")
		set(value) {
			value?.let {
				attributes["formaction"] = it
			}
		}

	var formenctype: String?
		get() = attributes.getOrDefault("formenctype", "")
		set(value) {
			value?.let {
				attributes["formenctype"] = it
			}
		}

	var formmethod: String?
		get() = attributes.getOrDefault("formmethod", "")
		set(value) {
			value?.let {
				attributes["formmethod"] = it
			}
		}

	var formnovalidate: String?
		get() = attributes.getOrDefault("formnovalidate", "")
		set(value) {
			value?.let {
				attributes["formnovalidate"] = it
			}
		}

	var formtarget: String?
		get() = attributes.getOrDefault("formtarget", "")
		set(value) {
			value?.let {
				attributes["formtarget"] = it
			}
		}

	var name: String?
		get() = attributes.getOrDefault("name", "")
		set(value) {
			value?.let {
				attributes["name"] = it
			}
		}

	var styles: String?
		get() = attributes.getOrDefault("styles", "")
		set(value) {
			value?.let {
				attributes["styles"] = it
			}
		}

	var type: String?
		get() = attributes.getOrDefault("type", "")
		set(value) {
			value?.let {
				attributes["type"] = it
			}
		}

	var value: String?
		get() = attributes.getOrDefault("value", "")
		set(value) {
			value?.let {
				attributes["value"] = it
			}
		}

}

