package io.persephone.dsl.element

import io.persephone.dsl.HtmlTag
import io.persephone.dsl.HeadTag
import io.persephone.dsl.BodyTag
import io.persephone.dsl.EmptyTag

// generated by Generator.kt [process]
class HEAD : HeadTag("head") {


}

