package io.persephone.dsl.element

import io.persephone.dsl.*

// generated by Generator.kt [process]
class IMG : BodyTag("img") {

	var alt: String?
		get() = attributes.getOrDefault("alt", "")
		set(value) {
			value?.let {
				attributes["alt"] = it
			}
		}

	var classes: String?
		get() = attributes.getOrDefault("classes", "")
		set(value) {
			value?.let {
				attributes["classes"] = it
			}
		}

	var crossorigin: String?
		get() = attributes.getOrDefault("crossorigin", "")
		set(value) {
			value?.let {
				attributes["crossorigin"] = it
			}
		}

	var decoding: String?
		get() = attributes.getOrDefault("decoding", "")
		set(value) {
			value?.let {
				attributes["decoding"] = it
			}
		}

	var height: String?
		get() = attributes.getOrDefault("height", "")
		set(value) {
			value?.let {
				attributes["height"] = it
			}
		}

	var importance: String?
		get() = attributes.getOrDefault("importance", "")
		set(value) {
			value?.let {
				attributes["importance"] = it
			}
		}

	var ismap: String?
		get() = attributes.getOrDefault("ismap", "")
		set(value) {
			value?.let {
				attributes["ismap"] = it
			}
		}

	var loading: String?
		get() = attributes.getOrDefault("loading", "")
		set(value) {
			value?.let {
				attributes["loading"] = it
			}
		}

	var referrerpolicy: String?
		get() = attributes.getOrDefault("referrerpolicy", "")
		set(value) {
			value?.let {
				attributes["referrerpolicy"] = it
			}
		}

	var sizes: String?
		get() = attributes.getOrDefault("sizes", "")
		set(value) {
			value?.let {
				attributes["sizes"] = it
			}
		}

	var src: String?
		get() = attributes.getOrDefault("src", "")
		set(value) {
			value?.let {
				attributes["src"] = it
			}
		}

	var srcset: String?
		get() = attributes.getOrDefault("srcset", "")
		set(value) {
			value?.let {
				attributes["srcset"] = it
			}
		}

	var styles: String?
		get() = attributes.getOrDefault("styles", "")
		set(value) {
			value?.let {
				attributes["styles"] = it
			}
		}

	var usemap: String?
		get() = attributes.getOrDefault("usemap", "")
		set(value) {
			value?.let {
				attributes["usemap"] = it
			}
		}

	var width: String?
		get() = attributes.getOrDefault("width", "")
		set(value) {
			value?.let {
				attributes["width"] = it
			}
		}

}

