package io.persephone.dsl.element

import io.persephone.dsl.*

// generated by Generator.kt [process]
class INPUT : BodyTag("input") {

	var autocomplete: String?
		get() = attributes.getOrDefault("autocomplete", "")
		set(value) {
			value?.let {
				attributes["autocomplete"] = it
			}
		}

	var autofocus: String?
		get() = attributes.getOrDefault("autofocus", "")
		set(value) {
			value?.let {
				attributes["autofocus"] = it
			}
		}

	var classes: String?
		get() = attributes.getOrDefault("classes", "")
		set(value) {
			value?.let {
				attributes["classes"] = it
			}
		}

	var disabled: String?
		get() = attributes.getOrDefault("disabled", "")
		set(value) {
			value?.let {
				attributes["disabled"] = it
			}
		}

	var form: String?
		get() = attributes.getOrDefault("form", "")
		set(value) {
			value?.let {
				attributes["form"] = it
			}
		}

	var list: String?
		get() = attributes.getOrDefault("list", "")
		set(value) {
			value?.let {
				attributes["list"] = it
			}
		}

	var name: String?
		get() = attributes.getOrDefault("name", "")
		set(value) {
			value?.let {
				attributes["name"] = it
			}
		}

	var readonly: String?
		get() = attributes.getOrDefault("readonly", "")
		set(value) {
			value?.let {
				attributes["readonly"] = it
			}
		}

	var required: String?
		get() = attributes.getOrDefault("required", "")
		set(value) {
			value?.let {
				attributes["required"] = it
			}
		}

	var styles: String?
		get() = attributes.getOrDefault("styles", "")
		set(value) {
			value?.let {
				attributes["styles"] = it
			}
		}

	var tabindex: String?
		get() = attributes.getOrDefault("tabindex", "")
		set(value) {
			value?.let {
				attributes["tabindex"] = it
			}
		}

	var type: String?
		get() = attributes.getOrDefault("type", "")
		set(value) {
			value?.let {
				attributes["type"] = it
			}
		}

	var value: String?
		get() = attributes.getOrDefault("value", "")
		set(value) {
			value?.let {
				attributes["value"] = it
			}
		}

}

