package io.persephone.dsl.element

import io.persephone.dsl.*

// generated by HtmlDslGenerator.kt

open class LINK(
	href: String? = null,
	rel: String? = null,
	type: String? = null,
	tagName: String = "link",
	selfClosing: Boolean = true
) : Tag(
	tagName = tagName,
	selfClosing = selfClosing
) {

	var href: String?
		get() = attributes.get("href")
		set(value) {
			value?.let {
				attributes["href"] = it
			}
		}

	var rel: String?
		get() = attributes.get("rel")
		set(value) {
			value?.let {
				attributes["rel"] = it
			}
		}

	var type: String?
		get() = attributes.get("type")
		set(value) {
			value?.let {
				attributes["type"] = it
			}
		}

	init {
		this.href = href
		this.rel = rel
		this.type = type
	}

}
