package io.persephone.dsl.element

import io.persephone.dsl.*

@DslMarker
annotation class MetaMarker

// generated by HtmlDslGenerator.kt

@MetaMarker
class META(
	charset: String? = null,
	content: String? = null,
	name: String? = null
) : Tag(
	tagName = "meta",
	selfClosing = true
) {

	var charset: String?
		get() = attributes.get("charset")
		set(value) {
			value?.let {
				attributes["charset"] = it
			}
		}

	var content: String?
		get() = attributes.get("content")
		set(value) {
			value?.let {
				attributes["content"] = it
			}
		}

	var name: String?
		get() = attributes.get("name")
		set(value) {
			value?.let {
				attributes["name"] = it
			}
		}

	init {
		this.charset = charset
		this.content = content
		this.name = name
	}

}
