package io.persephone.dsl.element

import io.persephone.dsl.Tag
import io.persephone.dsl.element.*

@DslMarker
annotation class StyleMarker

// generated by HtmlDslGenerator.kt
@StyleMarker
class STYLE(
	media: String? = null,
	nonce: String? = null,
	title: String? = null,
	type: String? = null,
	init: (STYLE.() -> Unit)? = null
) : Tag(
	tagName = "style",
	selfClosing = false
) {

	var media: String?
		get() = attributes.get("media")
		set(value) {
			value?.let {
				attributes["media"] = it
			}
		}

	var nonce: String?
		get() = attributes.get("nonce")
		set(value) {
			value?.let {
				attributes["nonce"] = it
			}
		}

	var title: String?
		get() = attributes.get("title")
		set(value) {
			value?.let {
				attributes["title"] = it
			}
		}

	var type: String?
		get() = attributes.get("type")
		set(value) {
			value?.let {
				attributes["type"] = it
			}
		}

	init {
		this.media = media
		this.nonce = nonce
		this.title = title
		this.type = type
	}

}
