package io.persephone.dsl.element

import io.persephone.dsl.Tag
import io.persephone.dsl.element.*

// generated by HtmlDslGenerator.kt
class TITLE(
	init: (TITLE.() -> Unit)? = null
) : Tag(
	tagName = "title",
	selfClosing = false
) {

	init {
	}

}
