package io.persephone.dsl.element

import io.persephone.dsl.*

@DslMarker
annotation class TitleMarker

// generated by HtmlDslGenerator.kt

@TitleMarker
class TITLE(
	init: (TITLE.() -> Unit)? = null
) : Tag(
	tagName = "title",
	selfClosing = false
) {

	init {

		init?.invoke(this)
	}

	operator fun String.unaryPlus() {
		children.add(Text(this))
	}

}
