package io.jvaas.dsl.html.element

import io.jvaas.dsl.html.*
import io.jvaas.dsl.html.attribute.*
import io.jvaas.dsl.html.funtribute.*

// generated by HtmlDslGenerator.kt

open class BASE(
	href: String? = null,
	target: String? = null,
	tagName: String = "base",
	selfClosing: Boolean = true
) : AttrHref,  
	AttrTarget,  
	Tag( 
	tagName = tagName,
	selfClosing = selfClosing, 
) {

	init {
		this.href = href
		this.target = target
	}
}
