package io.jvaas.dsl.html.element

import io.jvaas.dsl.html.*
import io.jvaas.dsl.html.attribute.*
import io.jvaas.dsl.html.funtribute.*

// generated by HtmlDslGenerator.kt

open class HEAD(
	tagName: String = "head",
	selfClosing: Boolean = false,
	init: (HEAD.() -> Unit)? = null
) : FuntBase,  
	FuntLink,  
	FuntMeta,  
	FuntNoscript,  
	FuntScript,  
	FuntStyle,  
	FuntTitle,  
	Tag( 
	tagName = tagName,
	selfClosing = selfClosing, 
) {

	init {

		init?.invoke(this)
	}
}
