package io.jvaas.dsl.html.element

import io.jvaas.dsl.html.*
import io.jvaas.dsl.html.attribute.*
import io.jvaas.dsl.html.funtribute.*

// generated by HtmlDslGenerator.kt

open class LINK(
	href: String? = null,
	rel: String? = null,
	type: String? = null,
	tagName: String = "link",
	selfClosing: Boolean = true
) : AttrHref,  
	AttrRel,  
	AttrType,  
	Tag( 
	tagName = tagName,
	selfClosing = selfClosing, 
) {

	init {
		this.href = href
		this.rel = rel
		this.type = type
	}
}
