package io.jvaas.dsl.html.element

import io.jvaas.dsl.html.*
import io.jvaas.dsl.html.attribute.*
import io.jvaas.dsl.html.funtribute.*

// generated by HtmlDslGenerator.kt

open class META(
	charset: String? = null,
	content: String? = null,
	name: String? = null,
	tagName: String = "meta",
	selfClosing: Boolean = true
) : AttrCharset,  
	AttrConTent,  
	AttrName,  
	Tag( 
	tagName = tagName,
	selfClosing = selfClosing, 
) {

	init {
		this.charset = charset
		this.content = content
		this.name = name
	}
}
