package io.jvaas.dsl.html.element

import io.jvaas.dsl.html.*

// generated by HtmlDslGenerator.kt

open class STYLE(
	media: String? = null,
	nonce: String? = null,
	title: String? = null,
	type: String? = null,
	tagName: String = "style",
	selfClosing: Boolean = false,
	init: (STYLE.() -> Unit)? = null
) : Tag(
	tagName = tagName,
	selfClosing = selfClosing
) {

	var media: String?
		get() = attributes.get("media")
		set(value) {
			value?.let {
				attributes["media"] = it
			}
		}

	var nonce: String?
		get() = attributes.get("nonce")
		set(value) {
			value?.let {
				attributes["nonce"] = it
			}
		}

	var title: String?
		get() = attributes.get("title")
		set(value) {
			value?.let {
				attributes["title"] = it
			}
		}

	var type: String?
		get() = attributes.get("type")
		set(value) {
			value?.let {
				attributes["type"] = it
			}
		}

	init {
		this.media = media
		this.nonce = nonce
		this.title = title
		this.type = type

		init?.invoke(this)
	}

	operator fun String.unaryPlus() {
		children.add(Text(this))
	}

}
