package io.jvaas.dsl.html.element

import io.jvaas.dsl.html.*
import io.jvaas.dsl.html.attribute.*
import io.jvaas.dsl.html.funtribute.*

// generated by HtmlDslGenerator.kt

open class STYLE(
	media: String? = null,
	nonce: String? = null,
	title: String? = null,
	type: String? = null,
	tagName: String = "style",
	selfClosing: Boolean = false,
	init: (STYLE.() -> Unit)? = null
) : AttrMedia,  
	AttrNonCe,  
	AttrTitle,  
	AttrType,  
	Tag( 
	tagName = tagName,
	selfClosing = selfClosing, 
) {

	init {
		this.media = media
		this.nonce = nonce
		this.title = title
		this.type = type

		init?.invoke(this)
	}
}
