package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnTimeupdate : Attr {
	var ontimeupdate: String?
		get() = attributes["ontimeupdate"]
		set(value) {
			value?.let {
				attributes["ontimeupdate"] = it
			}
		}
}	
