package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrIs : Attr {
	var `is`: String?
		get() = attributes["is"]
		set(value) {
			value?.let {
				attributes["is"] = it
			}
		}
}	
