package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrEmptied : Attr {
	var emptied: String?
		get() = attributes["emptied"]
		set(value) {
			value?.let {
				attributes["emptied"] = it
			}
		}
}	
