package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrTabindex : Attr {
	var tabindex: String?
		get() = attributes["tabindex"]
		set(value) {
			value?.let {
				attributes["tabindex"] = it
			}
		}
}	
