package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrIcon : Attr {
	var icon: String?
		get() = attributes["icon"]
		set(value) {
			value?.let {
				attributes["icon"] = it
			}
		}
}	
