package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrStep : Attr {
	var step: String?
		get() = attributes["step"]
		set(value) {
			value?.let {
				attributes["step"] = it
			}
		}
}	
