package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrReadonLy : Attr {
	var readonly: String?
		get() = attributes["readonly"]
		set(value) {
			value?.let {
				attributes["readonly"] = it
			}
		}
}	
