package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnBeforeunload : Attr {
	var onbeforeunload: String?
		get() = attributes["onbeforeunload"]
		set(value) {
			value?.let {
				attributes["onbeforeunload"] = it
			}
		}
}	
