package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrDownload : Attr {
	var download: String?
		get() = attributes["download"]
		set(value) {
			value?.let {
				attributes["download"] = it
			}
		}
}	
