package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrData : Attr {
	var data: String?
		get() = attributes["data"]
		set(value) {
			value?.let {
				attributes["data"] = it
			}
		}
}	
