package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrScope : Attr {
	var scope: String?
		get() = attributes["scope"]
		set(value) {
			value?.let {
				attributes["scope"] = it
			}
		}
}	
