package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrAutofocus : Attr {
	var autofocus: String?
		get() = attributes["autofocus"]
		set(value) {
			value?.let {
				attributes["autofocus"] = it
			}
		}
}	
