package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrConTent : Attr {
	var content: String?
		get() = attributes["content"]
		set(value) {
			value?.let {
				attributes["content"] = it
			}
		}
}	
