package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrRowspan : Attr {
	var rowspan: String?
		get() = attributes["rowspan"]
		set(value) {
			value?.let {
				attributes["rowspan"] = it
			}
		}
}	
