package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrPlaysinline : Attr {
	var playsinline: String?
		get() = attributes["playsinline"]
		set(value) {
			value?.let {
				attributes["playsinline"] = it
			}
		}
}	
