package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnMouseenter : Attr {
	var onmouseenter: String?
		get() = attributes["onmouseenter"]
		set(value) {
			value?.let {
				attributes["onmouseenter"] = it
			}
		}
}	
