package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrVolumechange : Attr {
	var volumechange: String?
		get() = attributes["volumechange"]
		set(value) {
			value?.let {
				attributes["volumechange"] = it
			}
		}
}	
