package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrCharset : Attr {
	var charset: String?
		get() = attributes["charset"]
		set(value) {
			value?.let {
				attributes["charset"] = it
			}
		}
}	
