package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrAutoplay : Attr {
	var autoplay: String?
		get() = attributes["autoplay"]
		set(value) {
			value?.let {
				attributes["autoplay"] = it
			}
		}
}	
