package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnOffline : Attr {
	var onoffline: String?
		get() = attributes["onoffline"]
		set(value) {
			value?.let {
				attributes["onoffline"] = it
			}
		}
}	
