package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrWidth : Attr {
	var width: String?
		get() = attributes["width"]
		set(value) {
			value?.let {
				attributes["width"] = it
			}
		}
}	
