package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnError : Attr {
	var onerror: String?
		get() = attributes["onerror"]
		set(value) {
			value?.let {
				attributes["onerror"] = it
			}
		}
}	
