package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrAudioprocess : Attr {
	var audioprocess: String?
		get() = attributes["audioprocess"]
		set(value) {
			value?.let {
				attributes["audioprocess"] = it
			}
		}
}	
