package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnShow : Attr {
	var onshow: String?
		get() = attributes["onshow"]
		set(value) {
			value?.let {
				attributes["onshow"] = it
			}
		}
}	
