package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrLoadedmetadata : Attr {
	var loadedmetadata: String?
		get() = attributes["loadedmetadata"]
		set(value) {
			value?.let {
				attributes["loadedmetadata"] = it
			}
		}
}	
