package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrConTrols : Attr {
	var controls: String?
		get() = attributes["controls"]
		set(value) {
			value?.let {
				attributes["controls"] = it
			}
		}
}	
