package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrHref : Attr {
	var href: String?
		get() = attributes["href"]
		set(value) {
			value?.let {
				attributes["href"] = it
			}
		}
}	
