package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrTarget : Attr {
	var target: String?
		get() = attributes["target"]
		set(value) {
			value?.let {
				attributes["target"] = it
			}
		}
}	
