package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrSeeked : Attr {
	var seeked: String?
		get() = attributes["seeked"]
		set(value) {
			value?.let {
				attributes["seeked"] = it
			}
		}
}	
