package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnOnline : Attr {
	var ononline: String?
		get() = attributes["ononline"]
		set(value) {
			value?.let {
				attributes["ononline"] = it
			}
		}
}	
