package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnEnded : Attr {
	var onended: String?
		get() = attributes["onended"]
		set(value) {
			value?.let {
				attributes["onended"] = it
			}
		}
}	
