package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrPlaying : Attr {
	var playing: String?
		get() = attributes["playing"]
		set(value) {
			value?.let {
				attributes["playing"] = it
			}
		}
}	
