package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrSeeking : Attr {
	var seeking: String?
		get() = attributes["seeking"]
		set(value) {
			value?.let {
				attributes["seeking"] = it
			}
		}
}	
