package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrItemprop : Attr {
	var itemprop: String?
		get() = attributes["itemprop"]
		set(value) {
			value?.let {
				attributes["itemprop"] = it
			}
		}
}	
