package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrType : Attr {
	var type: String?
		get() = attributes["type"]
		set(value) {
			value?.let {
				attributes["type"] = it
			}
		}
}	
