package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrSrcset : Attr {
	var srcset: String?
		get() = attributes["srcset"]
		set(value) {
			value?.let {
				attributes["srcset"] = it
			}
		}
}	
