package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrTitle : Attr {
	var title: String?
		get() = attributes["title"]
		set(value) {
			value?.let {
				attributes["title"] = it
			}
		}
}	
