package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnKeyup : Attr {
	var onkeyup: String?
		get() = attributes["onkeyup"]
		set(value) {
			value?.let {
				attributes["onkeyup"] = it
			}
		}
}	
