package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnEmptied : Attr {
	var onemptied: String?
		get() = attributes["onemptied"]
		set(value) {
			value?.let {
				attributes["onemptied"] = it
			}
		}
}	
