package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnUndo : Attr {
	var onundo: String?
		get() = attributes["onundo"]
		set(value) {
			value?.let {
				attributes["onundo"] = it
			}
		}
}	
