package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnWaiting : Attr {
	var onwaiting: String?
		get() = attributes["onwaiting"]
		set(value) {
			value?.let {
				attributes["onwaiting"] = it
			}
		}
}	
