package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnInvalid : Attr {
	var oninvalid: String?
		get() = attributes["oninvalid"]
		set(value) {
			value?.let {
				attributes["oninvalid"] = it
			}
		}
}	
