package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnLoad : Attr {
	var onload: String?
		get() = attributes["onload"]
		set(value) {
			value?.let {
				attributes["onload"] = it
			}
		}
}	
