package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnCuechange : Attr {
	var oncuechange: String?
		get() = attributes["oncuechange"]
		set(value) {
			value?.let {
				attributes["oncuechange"] = it
			}
		}
}	
