package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrPlaceholder : Attr {
	var placeholder: String?
		get() = attributes["placeholder"]
		set(value) {
			value?.let {
				attributes["placeholder"] = it
			}
		}
}	
