package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrAcceptCharset : Attr {
	var acceptCharset: String?
		get() = attributes["accept-charset"]
		set(value) {
			value?.let {
				attributes["accept-charset"] = it
			}
		}
}	
