package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnLoadedmetadata : Attr {
	var onloadedmetadata: String?
		get() = attributes["onloadedmetadata"]
		set(value) {
			value?.let {
				attributes["onloadedmetadata"] = it
			}
		}
}	
