package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrMethod : Attr {
	var method: String?
		get() = attributes["method"]
		set(value) {
			value?.let {
				attributes["method"] = it
			}
		}
}	
