package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrFormtarget : Attr {
	var formtarget: String?
		get() = attributes["formtarget"]
		set(value) {
			value?.let {
				attributes["formtarget"] = it
			}
		}
}	
