package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnToggle : Attr {
	var ontoggle: String?
		get() = attributes["ontoggle"]
		set(value) {
			value?.let {
				attributes["ontoggle"] = it
			}
		}
}	
