package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrCrossorigin : Attr {
	var crossorigin: String?
		get() = attributes["crossorigin"]
		set(value) {
			value?.let {
				attributes["crossorigin"] = it
			}
		}
}	
