package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnRedo : Attr {
	var onredo: String?
		get() = attributes["onredo"]
		set(value) {
			value?.let {
				attributes["onredo"] = it
			}
		}
}	
