package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrChecked : Attr {
	var checked: String?
		get() = attributes["checked"]
		set(value) {
			value?.let {
				attributes["checked"] = it
			}
		}
}	
