package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnInput : Attr {
	var oninput: String?
		get() = attributes["oninput"]
		set(value) {
			value?.let {
				attributes["oninput"] = it
			}
		}
}	
