package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrStyle : Attr {
	var style: String?
		get() = attributes["style"]
		set(value) {
			value?.let {
				attributes["style"] = it
			}
		}
}	
