package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrNovalidate : Attr {
	var novalidate: String?
		get() = attributes["novalidate"]
		set(value) {
			value?.let {
				attributes["novalidate"] = it
			}
		}
}	
