package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrPoster : Attr {
	var poster: String?
		get() = attributes["poster"]
		set(value) {
			value?.let {
				attributes["poster"] = it
			}
		}
}	
