package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnSubmit : Attr {
	var onsubmit: String?
		get() = attributes["onsubmit"]
		set(value) {
			value?.let {
				attributes["onsubmit"] = it
			}
		}
}	
