package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrCite : Attr {
	var cite: String?
		get() = attributes["cite"]
		set(value) {
			value?.let {
				attributes["cite"] = it
			}
		}
}	
