package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnSort : Attr {
	var onsort: String?
		get() = attributes["onsort"]
		set(value) {
			value?.let {
				attributes["onsort"] = it
			}
		}
}	
