package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnClick : Attr {
	var onclick: String?
		get() = attributes["onclick"]
		set(value) {
			value?.let {
				attributes["onclick"] = it
			}
		}
}	
