package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnKeypress : Attr {
	var onkeypress: String?
		get() = attributes["onkeypress"]
		set(value) {
			value?.let {
				attributes["onkeypress"] = it
			}
		}
}	
