package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrCanplaythrough : Attr {
	var canplaythrough: String?
		get() = attributes["canplaythrough"]
		set(value) {
			value?.let {
				attributes["canplaythrough"] = it
			}
		}
}	
