package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrFormenctype : Attr {
	var formenctype: String?
		get() = attributes["formenctype"]
		set(value) {
			value?.let {
				attributes["formenctype"] = it
			}
		}
}	
