package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnDragleave : Attr {
	var ondragleave: String?
		get() = attributes["ondragleave"]
		set(value) {
			value?.let {
				attributes["ondragleave"] = it
			}
		}
}	
