package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrRel : Attr {
	var rel: String?
		get() = attributes["rel"]
		set(value) {
			value?.let {
				attributes["rel"] = it
			}
		}
}	
