package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrAccept : Attr {
	var accept: String?
		get() = attributes["accept"]
		set(value) {
			value?.let {
				attributes["accept"] = it
			}
		}
}	
