package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrLoadeddata : Attr {
	var loadeddata: String?
		get() = attributes["loadeddata"]
		set(value) {
			value?.let {
				attributes["loadeddata"] = it
			}
		}
}	
