package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrRadiogroup : Attr {
	var radiogroup: String?
		get() = attributes["radiogroup"]
		set(value) {
			value?.let {
				attributes["radiogroup"] = it
			}
		}
}	
