package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrId : Attr {
	var id: String?
		get() = attributes["id"]
		set(value) {
			value?.let {
				attributes["id"] = it
			}
		}
}	
