package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrMax : Attr {
	var max: String?
		get() = attributes["max"]
		set(value) {
			value?.let {
				attributes["max"] = it
			}
		}
}	
