package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrStart : Attr {
	var start: String?
		get() = attributes["start"]
		set(value) {
			value?.let {
				attributes["start"] = it
			}
		}
}	
