package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnBlur : Attr {
	var onblur: String?
		get() = attributes["onblur"]
		set(value) {
			value?.let {
				attributes["onblur"] = it
			}
		}
}	
