package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnAbort : Attr {
	var onabort: String?
		get() = attributes["onabort"]
		set(value) {
			value?.let {
				attributes["onabort"] = it
			}
		}
}	
