package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrDraggable : Attr {
	var draggable: String?
		get() = attributes["draggable"]
		set(value) {
			value?.let {
				attributes["draggable"] = it
			}
		}
}	
