package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnLoadstart : Attr {
	var onloadstart: String?
		get() = attributes["onloadstart"]
		set(value) {
			value?.let {
				attributes["onloadstart"] = it
			}
		}
}	
