package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrMedia : Attr {
	var media: String?
		get() = attributes["media"]
		set(value) {
			value?.let {
				attributes["media"] = it
			}
		}
}	
