package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrDisabled : Attr {
	var disabled: String?
		get() = attributes["disabled"]
		set(value) {
			value?.let {
				attributes["disabled"] = it
			}
		}
}	
