package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrItemid : Attr {
	var itemid: String?
		get() = attributes["itemid"]
		set(value) {
			value?.let {
				attributes["itemid"] = it
			}
		}
}	
