package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrItemref : Attr {
	var itemref: String?
		get() = attributes["itemref"]
		set(value) {
			value?.let {
				attributes["itemref"] = it
			}
		}
}	
