package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrList : Attr {
	var list: String?
		get() = attributes["list"]
		set(value) {
			value?.let {
				attributes["list"] = it
			}
		}
}	
