package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrLow : Attr {
	var low: String?
		get() = attributes["low"]
		set(value) {
			value?.let {
				attributes["low"] = it
			}
		}
}	
