package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrHeaders : Attr {
	var headers: String?
		get() = attributes["headers"]
		set(value) {
			value?.let {
				attributes["headers"] = it
			}
		}
}	
