package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrName : Attr {
	var name: String?
		get() = attributes["name"]
		set(value) {
			value?.let {
				attributes["name"] = it
			}
		}
}	
