package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrSize : Attr {
	var size: String?
		get() = attributes["size"]
		set(value) {
			value?.let {
				attributes["size"] = it
			}
		}
}	
