package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnMouseover : Attr {
	var onmouseover: String?
		get() = attributes["onmouseover"]
		set(value) {
			value?.let {
				attributes["onmouseover"] = it
			}
		}
}	
