package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrXmlns : Attr {
	var xmlns: String?
		get() = attributes["xmlns"]
		set(value) {
			value?.let {
				attributes["xmlns"] = it
			}
		}
}	
