package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrCapture : Attr {
	var capture: String?
		get() = attributes["capture"]
		set(value) {
			value?.let {
				attributes["capture"] = it
			}
		}
}	
