package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrRows : Attr {
	var rows: String?
		get() = attributes["rows"]
		set(value) {
			value?.let {
				attributes["rows"] = it
			}
		}
}	
