package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrSrcdoc : Attr {
	var srcdoc: String?
		get() = attributes["srcdoc"]
		set(value) {
			value?.let {
				attributes["srcdoc"] = it
			}
		}
}	
