package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrSrc : Attr {
	var src: String?
		get() = attributes["src"]
		set(value) {
			value?.let {
				attributes["src"] = it
			}
		}
}	
