package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnHashchange : Attr {
	var onhashchange: String?
		get() = attributes["onhashchange"]
		set(value) {
			value?.let {
				attributes["onhashchange"] = it
			}
		}
}	
