package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrAllowfullscreen : Attr {
	var allowfullscreen: String?
		get() = attributes["allowfullscreen"]
		set(value) {
			value?.let {
				attributes["allowfullscreen"] = it
			}
		}
}	
