package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnDragenter : Attr {
	var ondragenter: String?
		get() = attributes["ondragenter"]
		set(value) {
			value?.let {
				attributes["ondragenter"] = it
			}
		}
}	
