package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnUnload : Attr {
	var onunload: String?
		get() = attributes["onunload"]
		set(value) {
			value?.let {
				attributes["onunload"] = it
			}
		}
}	
