package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrProgress : Attr {
	var progress: String?
		get() = attributes["progress"]
		set(value) {
			value?.let {
				attributes["progress"] = it
			}
		}
}	
