package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnMousewheel : Attr {
	var onmousewheel: String?
		get() = attributes["onmousewheel"]
		set(value) {
			value?.let {
				attributes["onmousewheel"] = it
			}
		}
}	
