package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrAllowpaymentrequest : Attr {
	var allowpaymentrequest: String?
		get() = attributes["allowpaymentrequest"]
		set(value) {
			value?.let {
				attributes["allowpaymentrequest"] = it
			}
		}
}	
