package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrPing : Attr {
	var ping: String?
		get() = attributes["ping"]
		set(value) {
			value?.let {
				attributes["ping"] = it
			}
		}
}	
