package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrPreload : Attr {
	var preload: String?
		get() = attributes["preload"]
		set(value) {
			value?.let {
				attributes["preload"] = it
			}
		}
}	
