package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrMinlength : Attr {
	var minlength: String?
		get() = attributes["minlength"]
		set(value) {
			value?.let {
				attributes["minlength"] = it
			}
		}
}	
