package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnSuspend : Attr {
	var onsuspend: String?
		get() = attributes["onsuspend"]
		set(value) {
			value?.let {
				attributes["onsuspend"] = it
			}
		}
}	
