package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnProgress : Attr {
	var onprogress: String?
		get() = attributes["onprogress"]
		set(value) {
			value?.let {
				attributes["onprogress"] = it
			}
		}
}	
