package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnContextmenu : Attr {
	var oncontextmenu: String?
		get() = attributes["oncontextmenu"]
		set(value) {
			value?.let {
				attributes["oncontextmenu"] = it
			}
		}
}	
