package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnDragexit : Attr {
	var ondragexit: String?
		get() = attributes["ondragexit"]
		set(value) {
			value?.let {
				attributes["ondragexit"] = it
			}
		}
}	
