package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnMessage : Attr {
	var onmessage: String?
		get() = attributes["onmessage"]
		set(value) {
			value?.let {
				attributes["onmessage"] = it
			}
		}
}	
