package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrDecoding : Attr {
	var decoding: String?
		get() = attributes["decoding"]
		set(value) {
			value?.let {
				attributes["decoding"] = it
			}
		}
}	
