package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrValue : Attr {
	var value: String?
		get() = attributes["value"]
		set(value) {
			value?.let {
				attributes["value"] = it
			}
		}
}	
