package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnAutocompleteerror : Attr {
	var onautocompleteerror: String?
		get() = attributes["onautocompleteerror"]
		set(value) {
			value?.let {
				attributes["onautocompleteerror"] = it
			}
		}
}	
