package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnKeydown : Attr {
	var onkeydown: String?
		get() = attributes["onkeydown"]
		set(value) {
			value?.let {
				attributes["onkeydown"] = it
			}
		}
}	
