package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrAllow : Attr {
	var allow: String?
		get() = attributes["allow"]
		set(value) {
			value?.let {
				attributes["allow"] = it
			}
		}
}	
