package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrNomodule : Attr {
	var nomodule: String?
		get() = attributes["nomodule"]
		set(value) {
			value?.let {
				attributes["nomodule"] = it
			}
		}
}	
