package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrBuffered : Attr {
	var buffered: String?
		get() = attributes["buffered"]
		set(value) {
			value?.let {
				attributes["buffered"] = it
			}
		}
}	
