package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrSuspend : Attr {
	var suspend: String?
		get() = attributes["suspend"]
		set(value) {
			value?.let {
				attributes["suspend"] = it
			}
		}
}	
