package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrFormaction : Attr {
	var formaction: String?
		get() = attributes["formaction"]
		set(value) {
			value?.let {
				attributes["formaction"] = it
			}
		}
}	
