package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrAsync : Attr {
	var async: String?
		get() = attributes["async"]
		set(value) {
			value?.let {
				attributes["async"] = it
			}
		}
}	
