package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrCoords : Attr {
	var coords: String?
		get() = attributes["coords"]
		set(value) {
			value?.let {
				attributes["coords"] = it
			}
		}
}	
