package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrMultiple : Attr {
	var multiple: String?
		get() = attributes["multiple"]
		set(value) {
			value?.let {
				attributes["multiple"] = it
			}
		}
}	
