package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrForm : Attr {
	var form: String?
		get() = attributes["form"]
		set(value) {
			value?.let {
				attributes["form"] = it
			}
		}
}	
