package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrSandbox : Attr {
	var sandbox: String?
		get() = attributes["sandbox"]
		set(value) {
			value?.let {
				attributes["sandbox"] = it
			}
		}
}	
