package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrMin : Attr {
	var min: String?
		get() = attributes["min"]
		set(value) {
			value?.let {
				attributes["min"] = it
			}
		}
}	
