package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnCanplay : Attr {
	var oncanplay: String?
		get() = attributes["oncanplay"]
		set(value) {
			value?.let {
				attributes["oncanplay"] = it
			}
		}
}	
