package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrPlay : Attr {
	var play: String?
		get() = attributes["play"]
		set(value) {
			value?.let {
				attributes["play"] = it
			}
		}
}	
