package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrSrclang : Attr {
	var srclang: String?
		get() = attributes["srclang"]
		set(value) {
			value?.let {
				attributes["srclang"] = it
			}
		}
}	
