package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnFocus : Attr {
	var onfocus: String?
		get() = attributes["onfocus"]
		set(value) {
			value?.let {
				attributes["onfocus"] = it
			}
		}
}	
