package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrItemscope : Attr {
	var itemscope: String?
		get() = attributes["itemscope"]
		set(value) {
			value?.let {
				attributes["itemscope"] = it
			}
		}
}	
