package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrDir : Attr {
	var dir: String?
		get() = attributes["dir"]
		set(value) {
			value?.let {
				attributes["dir"] = it
			}
		}
}	
