package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrSelected : Attr {
	var selected: String?
		get() = attributes["selected"]
		set(value) {
			value?.let {
				attributes["selected"] = it
			}
		}
}	
