package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrTimeupdate : Attr {
	var timeupdate: String?
		get() = attributes["timeupdate"]
		set(value) {
			value?.let {
				attributes["timeupdate"] = it
			}
		}
}	
