package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrDefault : Attr {
	var default: String?
		get() = attributes["default"]
		set(value) {
			value?.let {
				attributes["default"] = it
			}
		}
}	
