package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrAction : Attr {
	var action: String?
		get() = attributes["action"]
		set(value) {
			value?.let {
				attributes["action"] = it
			}
		}
}	
