package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrDirname : Attr {
	var dirname: String?
		get() = attributes["dirname"]
		set(value) {
			value?.let {
				attributes["dirname"] = it
			}
		}
}	
