package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnDblclick : Attr {
	var ondblclick: String?
		get() = attributes["ondblclick"]
		set(value) {
			value?.let {
				attributes["ondblclick"] = it
			}
		}
}	
