package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrVolumechanged : Attr {
	var volumechanged: String?
		get() = attributes["volumechanged"]
		set(value) {
			value?.let {
				attributes["volumechanged"] = it
			}
		}
}	
