package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnStorage : Attr {
	var onstorage: String?
		get() = attributes["onstorage"]
		set(value) {
			value?.let {
				attributes["onstorage"] = it
			}
		}
}	
