package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrReversed : Attr {
	var reversed: String?
		get() = attributes["reversed"]
		set(value) {
			value?.let {
				attributes["reversed"] = it
			}
		}
}	
