package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrRatechange : Attr {
	var ratechange: String?
		get() = attributes["ratechange"]
		set(value) {
			value?.let {
				attributes["ratechange"] = it
			}
		}
}	
