package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnSelect : Attr {
	var onselect: String?
		get() = attributes["onselect"]
		set(value) {
			value?.let {
				attributes["onselect"] = it
			}
		}
}	
