package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrLoop : Attr {
	var loop: String?
		get() = attributes["loop"]
		set(value) {
			value?.let {
				attributes["loop"] = it
			}
		}
}	
