package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrHigh : Attr {
	var high: String?
		get() = attributes["high"]
		set(value) {
			value?.let {
				attributes["high"] = it
			}
		}
}	
