package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrKind : Attr {
	var kind: String?
		get() = attributes["kind"]
		set(value) {
			value?.let {
				attributes["kind"] = it
			}
		}
}	
