package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrIntegrity : Attr {
	var integrity: String?
		get() = attributes["integrity"]
		set(value) {
			value?.let {
				attributes["integrity"] = it
			}
		}
}	
