package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnPlay : Attr {
	var onplay: String?
		get() = attributes["onplay"]
		set(value) {
			value?.let {
				attributes["onplay"] = it
			}
		}
}	
