package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrStalled : Attr {
	var stalled: String?
		get() = attributes["stalled"]
		set(value) {
			value?.let {
				attributes["stalled"] = it
			}
		}
}	
