package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnChange : Attr {
	var onchange: String?
		get() = attributes["onchange"]
		set(value) {
			value?.let {
				attributes["onchange"] = it
			}
		}
}	
