package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnClose : Attr {
	var onclose: String?
		get() = attributes["onclose"]
		set(value) {
			value?.let {
				attributes["onclose"] = it
			}
		}
}	
