package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrReferrerpolicy : Attr {
	var referrerpolicy: String?
		get() = attributes["referrerpolicy"]
		set(value) {
			value?.let {
				attributes["referrerpolicy"] = it
			}
		}
}	
