package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrCurrentTime : Attr {
	var currentTime: String?
		get() = attributes["currentTime"]
		set(value) {
			value?.let {
				attributes["currentTime"] = it
			}
		}
}	
