package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOpen : Attr {
	var open: String?
		get() = attributes["open"]
		set(value) {
			value?.let {
				attributes["open"] = it
			}
		}
}	
