package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrSpan : Attr {
	var span: String?
		get() = attributes["span"]
		set(value) {
			value?.let {
				attributes["span"] = it
			}
		}
}	
