package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrDatetime : Attr {
	var datetime: String?
		get() = attributes["datetime"]
		set(value) {
			value?.let {
				attributes["datetime"] = it
			}
		}
}	
