package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrLang : Attr {
	var lang: String?
		get() = attributes["lang"]
		set(value) {
			value?.let {
				attributes["lang"] = it
			}
		}
}	
