package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrAbbr : Attr {
	var abbr: String?
		get() = attributes["abbr"]
		set(value) {
			value?.let {
				attributes["abbr"] = it
			}
		}
}	
