package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnDragover : Attr {
	var ondragover: String?
		get() = attributes["ondragover"]
		set(value) {
			value?.let {
				attributes["ondragover"] = it
			}
		}
}	
