package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrAutocomplete : Attr {
	var autocomplete: String?
		get() = attributes["autocomplete"]
		set(value) {
			value?.let {
				attributes["autocomplete"] = it
			}
		}
}	
