package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnPause : Attr {
	var onpause: String?
		get() = attributes["onpause"]
		set(value) {
			value?.let {
				attributes["onpause"] = it
			}
		}
}	
