package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnCancel : Attr {
	var oncancel: String?
		get() = attributes["oncancel"]
		set(value) {
			value?.let {
				attributes["oncancel"] = it
			}
		}
}	
