package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrDurationChange : Attr {
	var durationchange: String?
		get() = attributes["durationchange"]
		set(value) {
			value?.let {
				attributes["durationchange"] = it
			}
		}
}	
