package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrTypemustmatch : Attr {
	var typemustmatch: String?
		get() = attributes["typemustmatch"]
		set(value) {
			value?.let {
				attributes["typemustmatch"] = it
			}
		}
}	
