package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrEnctype : Attr {
	var enctype: String?
		get() = attributes["enctype"]
		set(value) {
			value?.let {
				attributes["enctype"] = it
			}
		}
}	
