package io.jvaas.dsl.html.attribute

// generated by HtmlDslGenerator.kt

interface AttrOnDragstart : Attr {
	var ondragstart: String?
		get() = attributes["ondragstart"]
		set(value) {
			value?.let {
				attributes["ondragstart"] = it
			}
		}
}	
