package io.jvaas.dsl.html.funtribute

import io.jvaas.dsl.html.element.HEAD

// generated by HtmlDslGenerator.kt

interface FuntHead : Funt {

	fun head(
		init: (HEAD.() -> Unit)? = null
	) = HEAD().let {
	
		it.resources = this.resources
		this.children.add(it)
	
	
		init?.invoke(it)
		it
	}

}
