package io.jvaas.dsl.html.funtribute

import io.jvaas.dsl.html.element.STYLE

// generated by HtmlDslGenerator.kt

interface FuntStyle : Funt {

	fun style(
		media: String? = null,
		nonce: String? = null,
		title: String? = null,
		type: String? = null,
		init: (STYLE.() -> Unit)? = null
	) = STYLE().let {
	
		it.resources = this.resources
		this.children.add(it)
	
		it.media = media
		it.nonce = nonce
		it.title = title
		it.type = type
	
		init?.invoke(it)
		it
	}

}
