package io.jvaas.dsl.html.funtribute

import io.jvaas.dsl.html.element.BASE

// generated by HtmlDslGenerator.kt

interface FuntBase : Funt {

	fun base(
		href: String? = null,
		target: String? = null
	) = BASE().let {
	
		it.resources = this.resources
		this.children.add(it)
	
		it.href = href
		it.target = target
	
		it
	}

}
