package io.persephone.dsl

import io.persephone.dsl.element.*

// generated by Generator.kt [processBasic]
abstract class BodyTag(tagName: String) : TagWithText(tagName) {
	fun address( 
		init: (ADDRESS.() -> Unit)? = null
	) = initTag(ADDRESS(), init).apply {
		this.selfClosing = false
	}
	fun article( 
		init: (ARTICLE.() -> Unit)? = null
	) = initTag(ARTICLE(), init).apply {
		this.selfClosing = false
	}
	fun aside( 
		init: (ASIDE.() -> Unit)? = null
	) = initTag(ASIDE(), init).apply {
		this.selfClosing = false
	}
	fun footer( 
		init: (FOOTER.() -> Unit)? = null
	) = initTag(FOOTER(), init).apply {
		this.selfClosing = false
	}
	fun header( 
		init: (HEADER.() -> Unit)? = null
	) = initTag(HEADER(), init).apply {
		this.selfClosing = false
	}
	fun h1( 
		init: (H1.() -> Unit)? = null
	) = initTag(H1(), init).apply {
		this.selfClosing = false
	}
	fun h2( 
		init: (H2.() -> Unit)? = null
	) = initTag(H2(), init).apply {
		this.selfClosing = false
	}
	fun h3( 
		init: (H3.() -> Unit)? = null
	) = initTag(H3(), init).apply {
		this.selfClosing = false
	}
	fun h4( 
		init: (H4.() -> Unit)? = null
	) = initTag(H4(), init).apply {
		this.selfClosing = false
	}
	fun h5( 
		init: (H5.() -> Unit)? = null
	) = initTag(H5(), init).apply {
		this.selfClosing = false
	}
	fun h6( 
		init: (H6.() -> Unit)? = null
	) = initTag(H6(), init).apply {
		this.selfClosing = false
	}
	fun hgroup( 
		init: (HGROUP.() -> Unit)? = null
	) = initTag(HGROUP(), init).apply {
		this.selfClosing = false
	}
	fun main( 
		init: (MAIN.() -> Unit)? = null
	) = initTag(MAIN(), init).apply {
		this.selfClosing = false
	}
	fun nav( 
		init: (NAV.() -> Unit)? = null
	) = initTag(NAV(), init).apply {
		this.selfClosing = false
	}
	fun section( 
		init: (SECTION.() -> Unit)? = null
	) = initTag(SECTION(), init).apply {
		this.selfClosing = false
	}
	fun blockquote( 
		init: (BLOCKQUOTE.() -> Unit)? = null
	) = initTag(BLOCKQUOTE(), init).apply {
		this.selfClosing = false
	}
	fun dd( 
		init: (DD.() -> Unit)? = null
	) = initTag(DD(), init).apply {
		this.selfClosing = false
	}
	fun dir( 
		init: (DIR.() -> Unit)? = null
	) = initTag(DIR(), init).apply {
		this.selfClosing = false
	}
	fun div( 
		init: (DIV.() -> Unit)? = null
	) = initTag(DIV(), init).apply {
		this.selfClosing = false
	}
	fun dl( 
		init: (DL.() -> Unit)? = null
	) = initTag(DL(), init).apply {
		this.selfClosing = false
	}
	fun dt( 
		init: (DT.() -> Unit)? = null
	) = initTag(DT(), init).apply {
		this.selfClosing = false
	}
	fun figcaption( 
		init: (FIGCAPTION.() -> Unit)? = null
	) = initTag(FIGCAPTION(), init).apply {
		this.selfClosing = false
	}
	fun figure( 
		init: (FIGURE.() -> Unit)? = null
	) = initTag(FIGURE(), init).apply {
		this.selfClosing = false
	}
	fun hr( 
		init: (HR.() -> Unit)? = null
	) = initTag(HR(), init).apply {
		this.selfClosing = false
	}
	fun li( 
		init: (LI.() -> Unit)? = null
	) = initTag(LI(), init).apply {
		this.selfClosing = false
	}
	fun ol( 
		init: (OL.() -> Unit)? = null
	) = initTag(OL(), init).apply {
		this.selfClosing = false
	}
	fun p( 
		init: (P.() -> Unit)? = null
	) = initTag(P(), init).apply {
		this.selfClosing = false
	}
	fun pre( 
		init: (PRE.() -> Unit)? = null
	) = initTag(PRE(), init).apply {
		this.selfClosing = false
	}
	fun ul( 
		init: (UL.() -> Unit)? = null
	) = initTag(UL(), init).apply {
		this.selfClosing = false
	}
	fun a( 
		download: String? = null,
		href: String? = null,
		hreflang: String? = null,
		media: String? = null,
		ping: String? = null,
		referrerpolicy: String? = null,
		rel: String? = null,
		target: String? = null,
		type: String? = null,
		init: (A.() -> Unit)? = null
	) = initTag(A(), init).apply {
		this.selfClosing = false
		this.download = download
		this.href = href
		this.hreflang = hreflang
		this.media = media
		this.ping = ping
		this.referrerpolicy = referrerpolicy
		this.rel = rel
		this.target = target
		this.type = type
	}
	fun abbr( 
		init: (ABBR.() -> Unit)? = null
	) = initTag(ABBR(), init).apply {
		this.selfClosing = false
	}
	fun b( 
		init: (B.() -> Unit)? = null
	) = initTag(B(), init).apply {
		this.selfClosing = false
	}
	fun bdi( 
		init: (BDI.() -> Unit)? = null
	) = initTag(BDI(), init).apply {
		this.selfClosing = false
	}
	fun bdo( 
		init: (BDO.() -> Unit)? = null
	) = initTag(BDO(), init).apply {
		this.selfClosing = false
	}
	fun br( 
		init: (BR.() -> Unit)? = null
	) = initTag(BR(), init).apply {
		this.selfClosing = true
	}
	fun cite( 
		init: (CITE.() -> Unit)? = null
	) = initTag(CITE(), init).apply {
		this.selfClosing = false
	}
	fun code( 
		init: (CODE.() -> Unit)? = null
	) = initTag(CODE(), init).apply {
		this.selfClosing = false
	}
	fun data( 
		init: (DATA.() -> Unit)? = null
	) = initTag(DATA(), init).apply {
		this.selfClosing = false
	}
	fun dfn( 
		init: (DFN.() -> Unit)? = null
	) = initTag(DFN(), init).apply {
		this.selfClosing = false
	}
	fun em( 
		init: (EM.() -> Unit)? = null
	) = initTag(EM(), init).apply {
		this.selfClosing = false
	}
	fun i( 
		init: (I.() -> Unit)? = null
	) = initTag(I(), init).apply {
		this.selfClosing = false
	}
	fun kbd( 
		init: (KBD.() -> Unit)? = null
	) = initTag(KBD(), init).apply {
		this.selfClosing = false
	}
	fun mark( 
		init: (MARK.() -> Unit)? = null
	) = initTag(MARK(), init).apply {
		this.selfClosing = false
	}
	fun q( 
		init: (Q.() -> Unit)? = null
	) = initTag(Q(), init).apply {
		this.selfClosing = false
	}
	fun rb( 
		init: (RB.() -> Unit)? = null
	) = initTag(RB(), init).apply {
		this.selfClosing = false
	}
	fun rp( 
		init: (RP.() -> Unit)? = null
	) = initTag(RP(), init).apply {
		this.selfClosing = false
	}
	fun rt( 
		init: (RT.() -> Unit)? = null
	) = initTag(RT(), init).apply {
		this.selfClosing = false
	}
	fun rtc( 
		init: (RTC.() -> Unit)? = null
	) = initTag(RTC(), init).apply {
		this.selfClosing = false
	}
	fun ruby( 
		init: (RUBY.() -> Unit)? = null
	) = initTag(RUBY(), init).apply {
		this.selfClosing = false
	}
	fun s( 
		init: (S.() -> Unit)? = null
	) = initTag(S(), init).apply {
		this.selfClosing = false
	}
	fun samp( 
		init: (SAMP.() -> Unit)? = null
	) = initTag(SAMP(), init).apply {
		this.selfClosing = false
	}
	fun small( 
		init: (SMALL.() -> Unit)? = null
	) = initTag(SMALL(), init).apply {
		this.selfClosing = false
	}
	fun span( 
		init: (SPAN.() -> Unit)? = null
	) = initTag(SPAN(), init).apply {
		this.selfClosing = false
	}
	fun strong( 
		init: (STRONG.() -> Unit)? = null
	) = initTag(STRONG(), init).apply {
		this.selfClosing = false
	}
	fun sub( 
		init: (SUB.() -> Unit)? = null
	) = initTag(SUB(), init).apply {
		this.selfClosing = false
	}
	fun sup( 
		init: (SUP.() -> Unit)? = null
	) = initTag(SUP(), init).apply {
		this.selfClosing = false
	}
	fun time( 
		init: (TIME.() -> Unit)? = null
	) = initTag(TIME(), init).apply {
		this.selfClosing = false
	}
	fun tt( 
		init: (TT.() -> Unit)? = null
	) = initTag(TT(), init).apply {
		this.selfClosing = false
	}
	fun u( 
		init: (U.() -> Unit)? = null
	) = initTag(U(), init).apply {
		this.selfClosing = false
	}
	fun varx( 
		init: (VARX.() -> Unit)? = null
	) = initTag(VARX(), init).apply {
		this.selfClosing = false
	}
	fun wbr( 
		init: (WBR.() -> Unit)? = null
	) = initTag(WBR(), init).apply {
		this.selfClosing = false
	}
	fun area( 
		init: (AREA.() -> Unit)? = null
	) = initTag(AREA(), init).apply {
		this.selfClosing = false
	}
	fun audio( 
		init: (AUDIO.() -> Unit)? = null
	) = initTag(AUDIO(), init).apply {
		this.selfClosing = false
	}
	fun img( 
		crossorigin: String? = null,
		decoding: String? = null,
		height: String? = null,
		importance: String? = null,
		ismap: String? = null,
		loading: String? = null,
		referrerpolicy: String? = null,
		sizes: String? = null,
		src: String? = null,
		srcset: String? = null,
		width: String? = null,
		usemap: String? = null,
		init: (IMG.() -> Unit)? = null
	) = initTag(IMG(), init).apply {
		this.selfClosing = true
		this.crossorigin = crossorigin
		this.decoding = decoding
		this.height = height
		this.importance = importance
		this.ismap = ismap
		this.loading = loading
		this.referrerpolicy = referrerpolicy
		this.sizes = sizes
		this.src = src
		this.srcset = srcset
		this.width = width
		this.usemap = usemap
	}
	fun map( 
		init: (MAP.() -> Unit)? = null
	) = initTag(MAP(), init).apply {
		this.selfClosing = false
	}
	fun track( 
		init: (TRACK.() -> Unit)? = null
	) = initTag(TRACK(), init).apply {
		this.selfClosing = false
	}
	fun video( 
		init: (VIDEO.() -> Unit)? = null
	) = initTag(VIDEO(), init).apply {
		this.selfClosing = false
	}
	fun applet( 
		init: (APPLET.() -> Unit)? = null
	) = initTag(APPLET(), init).apply {
		this.selfClosing = false
	}
	fun embed( 
		init: (EMBED.() -> Unit)? = null
	) = initTag(EMBED(), init).apply {
		this.selfClosing = false
	}
	fun iframe( 
		init: (IFRAME.() -> Unit)? = null
	) = initTag(IFRAME(), init).apply {
		this.selfClosing = false
	}
	fun noembed( 
		init: (NOEMBED.() -> Unit)? = null
	) = initTag(NOEMBED(), init).apply {
		this.selfClosing = false
	}
	fun objectx( 
		init: (OBJECTX.() -> Unit)? = null
	) = initTag(OBJECTX(), init).apply {
		this.selfClosing = false
	}
	fun param( 
		init: (PARAM.() -> Unit)? = null
	) = initTag(PARAM(), init).apply {
		this.selfClosing = false
	}
	fun picture( 
		init: (PICTURE.() -> Unit)? = null
	) = initTag(PICTURE(), init).apply {
		this.selfClosing = false
	}
	fun source( 
		init: (SOURCE.() -> Unit)? = null
	) = initTag(SOURCE(), init).apply {
		this.selfClosing = false
	}
	fun canvas( 
		init: (CANVAS.() -> Unit)? = null
	) = initTag(CANVAS(), init).apply {
		this.selfClosing = false
	}
	fun noscript( 
		init: (NOSCRIPT.() -> Unit)? = null
	) = initTag(NOSCRIPT(), init).apply {
		this.selfClosing = false
	}
	fun script( 
		init: (SCRIPT.() -> Unit)? = null
	) = initTag(SCRIPT(), init).apply {
		this.selfClosing = false
	}
	fun del( 
		init: (DEL.() -> Unit)? = null
	) = initTag(DEL(), init).apply {
		this.selfClosing = false
	}
	fun ins( 
		init: (INS.() -> Unit)? = null
	) = initTag(INS(), init).apply {
		this.selfClosing = false
	}
	fun caption( 
		init: (CAPTION.() -> Unit)? = null
	) = initTag(CAPTION(), init).apply {
		this.selfClosing = false
	}
	fun col( 
		init: (COL.() -> Unit)? = null
	) = initTag(COL(), init).apply {
		this.selfClosing = false
	}
	fun colgroup( 
		init: (COLGROUP.() -> Unit)? = null
	) = initTag(COLGROUP(), init).apply {
		this.selfClosing = false
	}
	fun table( 
		init: (TABLE.() -> Unit)? = null
	) = initTag(TABLE(), init).apply {
		this.selfClosing = false
	}
	fun tbody( 
		init: (TBODY.() -> Unit)? = null
	) = initTag(TBODY(), init).apply {
		this.selfClosing = false
	}
	fun td( 
		init: (TD.() -> Unit)? = null
	) = initTag(TD(), init).apply {
		this.selfClosing = false
	}
	fun tfoot( 
		init: (TFOOT.() -> Unit)? = null
	) = initTag(TFOOT(), init).apply {
		this.selfClosing = false
	}
	fun th( 
		init: (TH.() -> Unit)? = null
	) = initTag(TH(), init).apply {
		this.selfClosing = false
	}
	fun thead( 
		init: (THEAD.() -> Unit)? = null
	) = initTag(THEAD(), init).apply {
		this.selfClosing = false
	}
	fun tr( 
		init: (TR.() -> Unit)? = null
	) = initTag(TR(), init).apply {
		this.selfClosing = false
	}
	fun button( 
		autofocus: String? = null,
		autocomplete: String? = null,
		disabled: String? = null,
		form: String? = null,
		formaction: String? = null,
		formenctype: String? = null,
		formmethod: String? = null,
		formnovalidate: String? = null,
		formtarget: String? = null,
		name: String? = null,
		type: String? = null,
		value: String? = null,
		init: (BUTTON.() -> Unit)? = null
	) = initTag(BUTTON(), init).apply {
		this.selfClosing = true
		this.autofocus = autofocus
		this.autocomplete = autocomplete
		this.disabled = disabled
		this.form = form
		this.formaction = formaction
		this.formenctype = formenctype
		this.formmethod = formmethod
		this.formnovalidate = formnovalidate
		this.formtarget = formtarget
		this.name = name
		this.type = type
		this.value = value
	}
	fun datalist( 
		init: (DATALIST.() -> Unit)? = null
	) = initTag(DATALIST(), init).apply {
		this.selfClosing = false
	}
	fun fieldset( 
		init: (FIELDSET.() -> Unit)? = null
	) = initTag(FIELDSET(), init).apply {
		this.selfClosing = false
	}
	fun form( 
		init: (FORM.() -> Unit)? = null
	) = initTag(FORM(), init).apply {
		this.selfClosing = false
	}
	fun input( 
		autocomplete: String? = null,
		autofocus: String? = null,
		disabled: String? = null,
		form: String? = null,
		list: String? = null,
		name: String? = null,
		readonly: String? = null,
		required: String? = null,
		tabindex: String? = null,
		type: String? = null,
		value: String? = null,
		init: (INPUT.() -> Unit)? = null
	) = initTag(INPUT(), init).apply {
		this.selfClosing = true
		this.autocomplete = autocomplete
		this.autofocus = autofocus
		this.disabled = disabled
		this.form = form
		this.list = list
		this.name = name
		this.readonly = readonly
		this.required = required
		this.tabindex = tabindex
		this.type = type
		this.value = value
	}
	fun label( 
		init: (LABEL.() -> Unit)? = null
	) = initTag(LABEL(), init).apply {
		this.selfClosing = false
	}
	fun legend( 
		init: (LEGEND.() -> Unit)? = null
	) = initTag(LEGEND(), init).apply {
		this.selfClosing = false
	}
	fun meter( 
		init: (METER.() -> Unit)? = null
	) = initTag(METER(), init).apply {
		this.selfClosing = false
	}
	fun optgroup( 
		init: (OPTGROUP.() -> Unit)? = null
	) = initTag(OPTGROUP(), init).apply {
		this.selfClosing = false
	}
	fun option( 
		init: (OPTION.() -> Unit)? = null
	) = initTag(OPTION(), init).apply {
		this.selfClosing = false
	}
	fun output( 
		init: (OUTPUT.() -> Unit)? = null
	) = initTag(OUTPUT(), init).apply {
		this.selfClosing = false
	}
	fun progress( 
		init: (PROGRESS.() -> Unit)? = null
	) = initTag(PROGRESS(), init).apply {
		this.selfClosing = false
	}
	fun select( 
		init: (SELECT.() -> Unit)? = null
	) = initTag(SELECT(), init).apply {
		this.selfClosing = false
	}
	fun textarea( 
		init: (TEXTAREA.() -> Unit)? = null
	) = initTag(TEXTAREA(), init).apply {
		this.selfClosing = false
	}
	fun details( 
		init: (DETAILS.() -> Unit)? = null
	) = initTag(DETAILS(), init).apply {
		this.selfClosing = false
	}
	fun dialog( 
		init: (DIALOG.() -> Unit)? = null
	) = initTag(DIALOG(), init).apply {
		this.selfClosing = false
	}
	fun menu( 
		init: (MENU.() -> Unit)? = null
	) = initTag(MENU(), init).apply {
		this.selfClosing = false
	}
	fun menuitem( 
		init: (MENUITEM.() -> Unit)? = null
	) = initTag(MENUITEM(), init).apply {
		this.selfClosing = false
	}
	fun summary( 
		init: (SUMMARY.() -> Unit)? = null
	) = initTag(SUMMARY(), init).apply {
		this.selfClosing = false
	}
}
