package io.persephone.dsl

import io.persephone.dsl.element.*

// generated by Generator.kt [processBasic]
abstract class HeadTag(tagName: String) : TagWithText(tagName) {
	fun link(init: LINK.() -> Unit) = initTag(LINK(), init)
	fun meta(init: META.() -> Unit) = initTag(META(), init)
	fun style(init: STYLE.() -> Unit) = initTag(STYLE(), init)
	fun title(init: TITLE.() -> Unit) = initTag(TITLE(), init)
}
