package io.persephone.dsl

//import io.persephone.dsl.element.BODY
//import io.persephone.dsl.element.HEAD

// generated by Generator.kt [processBasic]
//abstract class HtmlTag(tagName: String) : TagWithText(tagName) {
//	fun head(init: HEAD.() -> Unit) = initTag(HEAD(), init)
//	fun body(init: BODY.() -> Unit) = initTag(BODY(), init)
//}
